apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp-deployment
  labels:
    app: webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
        - name: webapp
          image: bezve01/webapp:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      # Pod Port within the cluster
      port: 8080
      # targetPort is application listening port or containerPort
      targetPort: 8000
  type: NodePort
